<?php
/**
 * Cross-checks GC_Jalali against fixtures generated by the already-verified
 * Python implementation (priceceawler/jalali.py, itself checked against
 * `jdatetime` on 20,000 random dates). Run: php tests/test-jalali.php <fixtures.json>
 */

define('GC_STANDALONE_TEST', true);
require __DIR__ . '/../includes/class-gc-jalali.php';

$fixtures_path = $argv[1] ?? null;
if (!$fixtures_path || !is_file($fixtures_path)) {
    fwrite(STDERR, "usage: php test-jalali.php <fixtures.json>\n");
    exit(2);
}

$fixtures = json_decode(file_get_contents($fixtures_path), true);
$failures = 0;
$checked = 0;

foreach ($fixtures as $case) {
    list($gy, $gm, $gd) = $case['g'];
    list($ejy, $ejm, $ejd) = $case['j'];

    // 1) gregorian_to_jalali must match Python's output exactly.
    list($jy, $jm, $jd) = GC_Jalali::gregorian_to_jalali($gy, $gm, $gd);
    $checked++;
    if ($jy !== $ejy || $jm !== $ejm || $jd !== $ejd) {
        $failures++;
        if ($failures <= 10) {
            fwrite(STDERR, sprintf(
                "MISMATCH g2j: %04d-%02d-%02d -> got %d/%d/%d, want %d/%d/%d\n",
                $gy, $gm, $gd, $jy, $jm, $jd, $ejy, $ejm, $ejd
            ));
        }
    }

    // 2) round trip: jalali_to_gregorian(gregorian_to_jalali(x)) == x.
    list($rgy, $rgm, $rgd) = GC_Jalali::jalali_to_gregorian($jy, $jm, $jd);
    $checked++;
    if ($rgy !== $gy || $rgm !== $gm || $rgd !== $gd) {
        $failures++;
        if ($failures <= 10) {
            fwrite(STDERR, sprintf(
                "MISMATCH round-trip: %d/%d/%d -> got %04d-%02d-%02d, want %04d-%02d-%02d\n",
                $jy, $jm, $jd, $rgy, $rgm, $rgd, $gy, $gm, $gd
            ));
        }
    }
}

// 3) a handful of hand-picked sanity checks independent of the fixtures.
$sanity_failures = 0;
$assert = function ($cond, $label) use (&$sanity_failures) {
    if (!$cond) {
        $sanity_failures++;
        fwrite(STDERR, "SANITY FAIL: {$label}\n");
    }
};

$assert(GC_Jalali::jalali_to_gregorian(1404, 1, 1) === array(2025, 3, 21), '1404/01/01 == 2025-03-21');
$assert(GC_Jalali::is_leap_year(1403) === true, '1403 is a leap year');
$assert(GC_Jalali::is_leap_year(1404) === false, '1404 is not a leap year');
$assert(GC_Jalali::days_in_month(1403, 12) === 30, 'Esfand 1403 has 30 days');
$assert(GC_Jalali::days_in_month(1404, 12) === 29, 'Esfand 1404 has 29 days');
$assert(GC_Jalali::weekday_name(1404, 1, 1) === 'جمعه', '1404/01/01 is a Friday');
$assert(GC_Jalali::weekday_name(1404, 1, 2) === 'شنبه', '1404/01/02 is a Saturday');
$assert(GC_Jalali::parse('1404/01/09') === array(1404, 1, 9), 'parse plain');
$assert(GC_Jalali::parse('۱۴۰۴/۰۱/۰۹') === array(1404, 1, 9), 'parse Persian digits');
$assert(GC_Jalali::parse('1404-1-9') === array(1404, 1, 9), 'parse dash separator');
$assert(GC_Jalali::parse('1404/13/01') === null, 'reject invalid month');
$assert(GC_Jalali::parse('1404/01/32') === null, 'reject invalid day');
$assert(GC_Jalali::add_days(1404, 1, 1, -1) === array(1403, 12, 30), 'add_days across year boundary');
$assert(GC_Jalali::diff_days(1404, 1, 1, 1404, 2, 1) === 31, 'diff_days one month');
$assert(count(GC_Jalali::date_range(1404, 1, 1, 1404, 1, 10)) === 10, 'date_range inclusive count');

echo "checked: {$checked} cross-checks over " . count($fixtures) . " fixtures\n";
echo "cross-check failures: {$failures}\n";
echo "sanity failures: {$sanity_failures}\n";

exit(($failures > 0 || $sanity_failures > 0) ? 1 : 0);
